labels:
  istio-injection: "enabled"
service:
  allocateLoadBalancerNodePorts: "true"
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${certificate_arn}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/load-balancer-source-ranges: "${cidr_range}"
    service.beta.kubernetes.io/aws-load-balancer-target-node-labels: role=infra
#    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "31036"

nodeSelector:
  role: infra

tolerations:
  - key: "role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

resources:
  requests:
    cpu: 75m
    memory: 250Mi
  limits:
    cpu: 150m
    memory: 1Gi

priorityClassName: "system-cluster-critical"